.PHONY: clients
.DEFAULT_GOAL := clients
# Re-create autogenerated client code from OpenAPI spec
# kiota generate -l python -d http://moma-management:5000/openapi.json -o generated/moma_management -c MomaManagementClient

clients:
	rm -rf generated
	kiota generate --clear-cache --ll Debug -l python -d http://172.23.0.1:5000/openapi.json -o generated/ap_management -c ApManagementClient