#!make
include .env
.PHONY: clients
.DEFAULT_GOAL := clients

# Re-create autogenerated client code from OpenAPI spec
# kiota generate -l python -d http://moma-management:5000/openapi.json -o generated/moma_management -c MomaManagementClient
MOMA_MANAGEMENT_URL ?= $(or $(MOMA_MANAGEMENT_SERVICE_URL),http://moma-management:5000)
# ap-management's and ap-executor's specs are vendored (openapi/*.json) so
# `make clients` works offline and doesn't depend on which image is running.
# Refresh them with:
#   curl -s http://ap-management:5000/openapi.json > openapi/ap_management.json
#   curl -s http://ap-executor:5000/openapi.json > openapi/ap_executor.json
AP_MANAGEMENT_SPEC ?= openapi/ap_management.json
AP_EXECUTOR_SPEC ?= openapi/ap_executor.json

clients:
	rm -rf generated
	echo "Generating clients from OpenAPI specs..."
	echo "MOMA_MANAGEMENT_URL=${MOMA_MANAGEMENT_URL}"
	echo "AP_MANAGEMENT_SPEC=${AP_MANAGEMENT_SPEC}"
	echo "AP_EXECUTOR_SPEC=${AP_EXECUTOR_SPEC}"
	kiota generate --clear-cache --ll Debug -l python -d ${MOMA_MANAGEMENT_URL}/openapi.json -o generated/moma_management -c MomaManagementClient
	kiota generate --clear-cache --ll Debug -l python -d ${AP_MANAGEMENT_SPEC} -o generated/ap_management -c ApManagementClient
	kiota generate --clear-cache --ll Debug -l python -d ${AP_EXECUTOR_SPEC} -o generated/ap_executor -c ApExecutorClient
