#!make
include .env
.PHONY: clients
.DEFAULT_GOAL := clients

# Re-create autogenerated client code from OpenAPI spec
# kiota generate -l python -d http://moma-management:5000/openapi.json -o generated/moma_management -c MomaManagementClient
MOMA_MANAGEMENT_URL ?= $(or $(MOMA_MANAGEMENT_SERVICE_URL),http://moma-management:5000)
AP_MANAGEMENT_URL ?= $(or $(AP_MANAGEMENT_SERVICE_URL),http://ap-management:5000)

clients:
	rm -rf generated
	echo "Generating clients from OpenAPI specs..."
	echo "MOMA_MANAGEMENT_URL=${MOMA_MANAGEMENT_URL}"
	echo "AP_MANAGEMENT_URL=${AP_MANAGEMENT_URL}"
	kiota generate --clear-cache --ll Debug -l python -d ${MOMA_MANAGEMENT_URL}/openapi.json -o generated/moma_management -c MomaManagementClient
	kiota generate --clear-cache --ll Debug -l python -d ${AP_MANAGEMENT_URL}/openapi.json -o generated/ap_management -c ApManagementClient